# Generated by Django 5.1.3 on 2025-03-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmasApp', '0005_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
